package com.example.callRest.testPkg;

import java.util.Arrays;

public class DuplicateTest {
	
	public static void main(String[] args) {
		
		
		String[] columns = new String[5];
//		
//		columns[0] = "ram";
//		columns[1] = "shy";
//		columns[2] = "har";
		
//		System.out.println(columns.toString());
//		System.out.println(columns.length);
//		
//		String str = "		AADHAR_CONSENT^\"ACCOUNT_NAME\"^\"ACCTYPE\"^\"ADDRESS\"^\"AGREEMENT_DATE\"^\"AML_DECLARATION\"^\"AML_QUEUE\"^\"AML_QUEUE_INDI\"^\"AML_QUEUE_SOLE\"^\"APPROVAL_STATUS\"^\"APPROVED_DATE\"^\"AREA\"^\"BANK_NAME\"^\"BCITY\"^\"BCOUNTRY\"^\"BELONGS_AU\"^\"BLOCATION\"^\"BPINCODE\"^\"BRANCH_NAME\"^\"BRANCH_ID\"^\"BSTATE\"^\"BUSINESS_ADDRESS\"^\"BUSINESS_ENTITY\"^\"BUSINESS_HOURSWEEKDAYS_FROM\"^\"BUSINESS_HOURSWEEKDAYS_TO\"^\"BUSINESS_INCOME\"^\"BUSINESS_NAME\"^\"BUSINESS_NATURE\"^\"BUSINESS_SUB_CATEGORY\"^\"CHARGE\"^\"CHARGES_TYPE\"^\"CITY\"^\"COD_AADHAR_NO\"^\"COD_ACCT_NO\"^\"CONSENT\"^\"CKYC_CITY\"^\"CKYC_PINCODE\"^\"CKYC_COUNTRY\"^\"CKYC_REGISTERED_ADDRESS\"^\"CKYC_STATE\"^\"COUNTRY\"^\"CREATED_BY\"^\"CREATED_DATE\"^\"CUSTOMER_ID\"^\"DOB\"^\"DISTRICT\"^\"ECITY\"^\"ECOUNTRY\"^\"EDAILY_TRANSACTIONS\"^\"EDUCATION_QUALIFICATION\"^\"EMAIL\"^\"EMAIL_OF_ENTITY_CUSTID\"^\"EMONTHLY_TRANSACTIONS\"^\"EMPLOYMENT_STATUS\"^\"ENTITY_COMMUNICATION_ADDRESS\"^\"ENTITY_DATE_OF_INCORPORATION\"^\"ENTITY_REGISTERED_ADDRESS\"^\"ENTITY_REGISTERED_NAME\"^\"ENTITY_SHORT_NAME\"^\"EPINCODE\"^\"ESTATE\"^\"ETRANSACTIONS_DAILY_COUNT\"^\"ETRANSACTIONS_MONTHLY_COUNT\"^\"ENTITY_AS_ADDRESSPROOF1\"^\"FATHER_NAME\"^\"FULL_NAME\"^\"FUTURE_AML_FLAG\"^\"GENDER\"^\"GROUP_ID\"^\"GST_ENABLED\"^\"GSTIN\"^\"GST_NUMBER\"^\"GST_STATE\"^\"HOUSE_NO\"^\"IFSC_CODE\"^\"LANDMARK\"^\"LAST_UPDATED_OP\"^\"LAST_UPDATED_SO\"^\"LC_CODE\"^\"LEAD_SOURCE\"^\"LG_CODE\"^\"MERCHANT_AGREEMENT\"^\"MERCHANT_NAME\"^\"MERCHANT_BUSINESS_INFO\"^\"MARITAL_STATUS\"^\"MOTHER_NAME\"^\"MASTER_MERCHANT\"^\"MERCHANT_TYPE\"^\"MICR_CODE\"^\"MID\"^\"MOBILE_NO\"^\"MODIFY_BY\"^\"MODIFY_DATE\"^\"NAME_MATCH_SCORE\"^\"OCCUPATION\"^\"OTHER_BUSINESS_ENTITY\"^\"OTHER_BUSINESS_NATURE\"^\"OTHER_BUSINESS_SUB_CATEGORY\"^\"OTP_VERIFY_DATE\"^\"PANCARD_NO\"^\"PAN_NUMBER_OF_ENTITY\"^\"PAN_VERIFY_ENTITY_NAME\"^\"PAN_VERIFY_MERCHANT_NAME\"^\"PEP\"^\"PSP_FEES\"^\"PINCODE\"^\"PLACE_OF_BIRTH\"^\"PRODUCTS_BRIEF_DESCRIPTION\"^\"PRODUCT_CODE\"^\"PSPFEES\"^\"REFERRAL_CODE\"^\"REMARK\"^\"REMOTE_MERCHANT_STATUS\"^\"RISK_CATEGORY\"^\"SALUTATION\"^\"SCORE\"^\"SEEDING\"^\"SELF_ONBOARD\"^\"SETTLEMENT_CYCLE\"^\"SHOP_MANAGER_MOBILENO\"^\"SHOP_MANAGER_NAME\"^\"STATE\"^\"STATUS\"^\"SWANIDHIYOJNA\"^\"TERM_AND_CONDITION\"^\"TIMESTAMP\"^\"TYPE_OF_PREMISES\"^\"USER_ID\"^\"VERIFY_ACCOUNT_NAME\"^\"VPA\"^\"WEBSITE\"\n"
//				+ ""
//	
		String str = "    ";
		
		System.out.println(str.length());
		System.out.println(str.trim() + "hh");
		System.out.println(str.trim().length());
		
		
		
		
	}

}
