package com.example.callRest.json;



public class GenerateStringType {

	public static String generateValidateCollectResponse(){
		String res = "{\"message\":\"SUCCESS\",\"data\":\"7Axff+lXyBrFFMfJctjpuk2ONqIVt71r514QvZxmWp6XRpLTIg6cox/5ND4AqEkf4oe+BUmcKpyUqErHw/5jl39ngJC0jMH40HRrtXVXgNrNBi6cjGmUJgPk+8kpH7mY0UHkIWkhZXyYDJQUyiCD0qzF1nmB6trwE++ewb5/v56P3qmmP0BScasdY18ZydT9vVyIQ0fNqZ0=\",\"status\":200}\n";
		return res;
	}
	public static String generateInititateJsonString() {
		String res = "{\n"
				+ "	\"merchantchanrgesShow\": null,\n"
				+ "	\"merchantemail\": \"anirudh@getepay.in\",\n"
				+ "	\"merchantProductIdDetails\": null,\n"
				+ "	\"qrpath\": null,\n"
				+ "	\"qrstring\": null,\n"
				+ "	\"transactionId\": \"515759859\",\n"
				+ "	\"enabledPayModes\": \"CC,DC,NB,wallet,NEFT,CHALLAN,\",\n"
				+ "	\"months\": [\"01\", \"02\", \"03\", \"04\", \"05\", \"06\", \"07\", \"08\", \"09\", \"10\", \"11\", \"12\"],\n"
				+ "	\"years\": [\"2025\", \"2026\", \"2027\", \"2028\", \"2029\", \"2030\", \"2031\", \"2032\", \"2033\", \"2034\", \"2035\", \"2036\", \"2037\", \"2038\", \"2039\", \"2040\", \"2041\", \"2042\", \"2043\", \"2044\", \"2045\", \"2046\", \"2047\", \"2048\", \"2049\", \"2050\", \"2051\", \"2052\", \"2053\", \"2054\"],\n"
				+ "	\"paymentRequest\": {\n"
				+ "		\"login\": \"TestMerchant\",\n"
				+ "		\"pass\": null,\n"
				+ "		\"amt\": \"1.0\",\n"
				+ "		\"paymentMode\": \"ALL\",\n"
				+ "		\"txncurr\": \"INR\",\n"
				+ "		\"merchantTxnId\": \"19164111\",\n"
				+ "		\"date\": \"2025-04-08\",\n"
				+ "		\"od\": null,\n"
				+ "		\"mobile\": null,\n"
				+ "		\"carddata\": null,\n"
				+ "		\"ru\": \"https://pay1.getepay.in:8443/getepayPortal/pg/paymentResponse\",\n"
				+ "		\"signature\": \"b7fe04126bfdba295cc9ef26da734df6aaef61573f482ec11a243c4385a6f9a616ba094aabc39ff581f14f3ca54586cd72ab8613e1aca0a194cd40c6318bfa08\",\n"
				+ "		\"bankid\": null,\n"
				+ "		\"transactionId\": 515759859,\n"
				+ "		\"requestType\": null,\n"
				+ "		\"paymentType\": null,\n"
				+ "		\"productType\": \"IPG\",\n"
				+ "		\"udf1\": \"siddharth\",\n"
				+ "		\"udf2\": \"6350043232\",\n"
				+ "		\"udf3\": \"siddharth@gmail.com\",\n"
				+ "		\"udf4\": \"4ee0927a7c3e36acd203\",\n"
				+ "		\"udf5\": \"GETEPAYESHF00000227|2023-03-09\",\n"
				+ "		\"txnType\": \"single\",\n"
				+ "		\"productDetails\": null,\n"
				+ "		\"van\": null,\n"
				+ "		\"name\": null,\n"
				+ "		\"ipAddress\": null,\n"
				+ "		\"memail\": null,\n"
				+ "		\"mnumber\": null\n"
				+ "	},\n"
				+ "	\"commissionModel\": {\n"
				+ "		\"amount\": 1.0,\n"
				+ "		\"charges\": 0,\n"
				+ "		\"total\": 1.0,\n"
				+ "		\"convenience\": null,\n"
				+ "		\"amountStr\": \"1.00\",\n"
				+ "		\"chargesStr\": \"0.00\",\n"
				+ "		\"totalStr\": \"1.00\",\n"
				+ "		\"convenienceStr\": null,\n"
				+ "		\"message\": null,\n"
				+ "		\"total2\": 1.0,\n"
				+ "		\"charges2\": 0\n"
				+ "	},\n"
				+ "	\"merchant\": {\n"
				+ "		\"mid\": 1,\n"
				+ "		\"merchantName\": \"Eshiksa Branch\",\n"
				+ "		\"email\": \"anirudh@getepay.in\",\n"
				+ "		\"mobileNumber\": \"9650278366\",\n"
				+ "		\"address\": \"Eshiksa, VKI\",\n"
				+ "		\"city\": \"Jaipur\",\n"
				+ "		\"state\": \"Rajasthan\",\n"
				+ "		\"pincode\": null,\n"
				+ "		\"businessCategory\": null,\n"
				+ "		\"accountNumber\": null,\n"
				+ "		\"ifscCode\": null,\n"
				+ "		\"bankName\": null\n"
				+ "	},\n"
				+ "	\"banks\": [{\n"
				+ "		\"id\": 1,\n"
				+ "		\"bankName\": \"State Bank of India\",\n"
				+ "		\"createdDate\": 1563821945406,\n"
				+ "		\"modifiedDate\": 1563821963420,\n"
				+ "		\"createdBy\": 1,\n"
				+ "		\"modifiedBy\": 1,\n"
				+ "		\"status\": true,\n"
				+ "		\"logoPath\": \"SbiBank.png\"\n"
				+ "	}, {\n"
				+ "		\"id\": 2,\n"
				+ "		\"bankName\": \"Punjab National Bank [Retail]\",\n"
				+ "		\"createdDate\": 1558612646937,\n"
				+ "		\"modifiedDate\": 1568565256388,\n"
				+ "		\"createdBy\": 1,\n"
				+ "		\"modifiedBy\": 1,\n"
				+ "		\"status\": true,\n"
				+ "		\"logoPath\": \"pnbBank.png\"\n"
				+ "	}],\n"
				+ "	\"wallets\": [{\n"
				+ "		\"id\": 30,\n"
				+ "		\"walletName\": \"Airtel Money\",\n"
				+ "		\"filePath\": \"Airtel.png\",\n"
				+ "		\"createdDate\": 1722943328000,\n"
				+ "		\"modifiedDate\": 1722943328000,\n"
				+ "		\"createdBy\": 1,\n"
				+ "		\"modifiedBy\": 1,\n"
				+ "		\"status\": true\n"
				+ "	}, {\n"
				+ "		\"id\": 32,\n"
				+ "		\"walletName\": \"Oxigen\",\n"
				+ "		\"filePath\": \"O.png\",\n"
				+ "		\"createdDate\": 1722943328000,\n"
				+ "		\"modifiedDate\": 1722943328000,\n"
				+ "		\"createdBy\": 1,\n"
				+ "		\"modifiedBy\": 1,\n"
				+ "		\"status\": true\n"
				+ "	}],\n"
				+ "	\"upiQrDetail\": {\n"
				+ "		\"id\": 1,\n"
				+ "		\"vpa\": \"getepay.merchant61062@icici\",\n"
				+ "		\"mid\": 1,\n"
				+ "		\"responseUrl\": \"https://portal.getepay.in:8443/getepayPortal/apis/upi_response\",\n"
				+ "		\"bankId\": 6,\n"
				+ "		\"gindex\": 0,\n"
				+ "		\"enable\": true,\n"
				+ "		\"merchantGenre\": \"OFFLINE\"\n"
				+ "	},\n"
				+ "	\"uicolorScheme\": {\n"
				+ "		\"id\": 19,\n"
				+ "		\"partnerId\": null,\n"
				+ "		\"primaryColor\": \"#02972f\",\n"
				+ "		\"secondaryColor\": null,\n"
				+ "		\"logoPath\": \"3FFdhCF7lmxlGNy+X8TqPtcekEhVo0updaBtEdmOOS+w_FJ2SnYNzU3mUa9SgQw8vqlJy4AVFfpschkLYK0XdA==\",\n"
				+ "		\"vpa\": \"getepay.merchant61062@icici\",\n"
				+ "		\"textHexaCode\": \"#ffffff\"\n"
				+ "	}\n"
				+ "}";
		return res;
	}
}
